package cc.vergence.features.enums;

public enum FontScales {
    SMOOTH_3F,
    SMOOTH_4F,
    SMOOTH_5F,
    SMOOTH_6F,
    SMOOTH_7F,
    SMOOTH_8F,
    SMOOTH_9F,
    SMOOTH_10F,
    SMOOTH_12F,
    SMOOTH_14F,
    SMOOTH_15F,
    SMOOTH_16F,
    SMOOTH_18F,
    SMOOTH_20F,
    SMOOTH_21F,
    SMOOTH_24F,
    SMOOTH_28F,
    SMOOTH_32F,

    SANS_3F,
    SANS_4F,
    SANS_5F,
    SANS_6F,
    SANS_7F,
    SANS_8F,
    SANS_9F,
    SANS_10F,
    SANS_12F,
    SANS_14F,
    SANS_15F,
    SANS_16F,
    SANS_18F,
    SANS_20F,
    SANS_21F,
    SANS_24F,
    SANS_28F,
    SANS_32F
}
